group: travis_latest
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
    include:
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35,coverage
        - python: 3.6
          env: TOX_ENV=py36
install:
    - pip install -r tests_requirements.txt
before_script:
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - pip3 install -e .
    - tox -e $TOX_ENV
    - pip3 uninstall -y allalgorithms
notifications:
    email: false
